---
title: "compile_plots"
author: "Philip Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r libs,warning=F}
## compile figures from plot panels
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(cowplot)
library(magick)
library(pdftools)
```

```{r source}
source("colour_palettes.R")
```

```{r empty_plot}
## Empty place holder
empty <- ggplot() +
          theme_bw() +
          theme(panel.border = element_blank())
```

```{r fig1}
## Load plot
## Temp flow chart load
flow_chart <- ggdraw() + draw_image(magick::image_read_pdf("plots/BriTROC-1_manuscript2_figure_1_v3-cropped.pdf",density = 600))
cohort_plot <- readRDS("plots/cohort_plot.RDS")
reg_surv_plot <- readRDS("plots/reg_surv_plot.RDS")

## Modify plot
cohort_plot <- cohort_plot +
                theme(legend.position = "none",
                      plot.title = element_blank())

reg_surv_plot <- reg_surv_plot +
                    theme(legend.position = "none")

## Get legends
cohort_legend  <- get_legend(
    cohort_plot + 
        guides(color = guide_legend(nrow = 2)) +
        theme(legend.position = "bottom",
              legend.direction = "vertical")
)

reg_surv_legend <- get_legend(
    reg_surv_plot + 
        #guides(fill = guide_legend(nrow = 1)) +
        theme(legend.position = "bottom",
              legend.direction = "vertical",
              legend.justification = c(0,0.5))
)

## Figure 1 compile
fig1 <- plot_grid(flow_chart,
                  plot_grid(cohort_plot,reg_surv_plot,
                            labels = c("B","C"),
                            rel_widths = c(0.6,0.4),
                            ncol = 2),
                  plot_grid(cohort_legend,
                            reg_surv_legend,
                            rel_widths = c(0.6,0.4),
                            ncol = 2,align = "v",axis = "t"),
                  labels = c("A","",""),
                  nrow = 3,rel_heights = c(0.45,0.45,0.1),align = "hv")

## Figure 1 render
ggsave2(filename = "plots/figure_1_render.png",plot = fig1,width = 9,height = 10,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_1_render.pdf",plot = fig1,width = 9,height = 10,units = "in",dpi = 300)
fig1
```

```{r fig2}
## Figure 2
# rendered in SNV analysis
```

```{r fig3}
## Load plots
substraction_plot <- readRDS("copy_number_analysis/broad_analysis/plots/genome_paired_substractionPlot.RDS") ## issues with PositionNudgeRepel error
substraction_plot <- ggdraw() + draw_image(magick::image_read_pdf("copy_number_analysis/broad_analysis/plots/genome_paired_substractionPlot.pdf",density = 300))
focal_rates_clinic <- readRDS("copy_number_analysis/focal_analysis/plots/amp_del_gene_plot_CNA.RDS")

## Modify plots
focal_rates_clinic <- focal_rates_clinic +
                        ylab("rate (%)") +
                        theme(legend.position = "bottom",
                              axis.text.x = element_text(hjust = 1))

## Figure 3 compile
fig3 <- plot_grid(substraction_plot,
                  focal_rates_clinic,
                  labels = c("A","B"),
                  nrow = 2)

## Figure 3 render
ggsave2(filename = "plots/figure_3_render.png",plot = fig3,width = 11,height = 8,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_3_render.pdf",plot = fig3,width = 11,height = 8,units = "in",dpi = 300)
fig3
```

```{r fig4}
## Load plots 
signature_stacked_all <- readRDS("copy_number_signatures/plots/signatures_allSamples_stacked_bar.RDS")
sig_box_wilcox <- readRDS("copy_number_signatures/plots/sig_box_wilcox.RDS")
sig_group_strat_pt <- readRDS("copy_number_signatures/plots/sig_group_strat_pt.RDS")

## Get legends
sig_legend_a <- get_legend(
    signature_stacked_all + 
        guides(fill = guide_legend(nrow = 1)) +
        theme(legend.position = "bottom")
)

sig_legend_b <- get_legend(
    sig_box_wilcox + 
        guides(fill = guide_legend(nrow = 1)) +
        theme(legend.position = "bottom")
)

## Modify plots
signature_stacked_all <- signature_stacked_all + theme(legend.position = "none")
sig_box_wilcox <- sig_box_wilcox + labs(title = "",caption = "") + theme(legend.position = "none")
sig_group_strat_pt <- sig_group_strat_pt + theme(legend.position = "none")

## Figure 4 compile
fig4 <- plot_grid(signature_stacked_all,
                  sig_box_wilcox,
                  sig_group_strat_pt,
                  plot_grid(sig_legend_a,sig_legend_b,ncol = 2,labels = c("","")),
                  nrow = 4,
                  rel_heights = c(0.5,0.5,0.9,0.1),
                  labels = c("A","B","C"))

## Figure 4 render
ggsave2(filename = "plots/figure_4_render.png",plot = fig4,width = 10,height = 12,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_4_render.pdf",plot = fig4,width = 10,height = 12,units = "in",dpi = 300)
fig4
```

```{r fig5}
## Load plots
signature_paired_line <- readRDS("copy_number_signatures/plots/paired_line_plot.RDS")
signature_stacked_alt <- readRDS("copy_number_signatures/plots/signatures_stacked_bar_alt.RDS")

# radar_plot <- ggdraw() + draw_image(magick::image_read_pdf("copy_number_signatures/plots/compile_radar.pdf",
#                                                       density = 600))
radar_plot <- readRDS("plots/arx_relapse_radar_partialILR_beta.RDS")
radar_plot <- radar_plot +
    labs(tag = "p=0.003, Wald test\np=0.052, Wald test (without s5)") +
    theme(plot.tag.position = c(0.80, 0.05),
          plot.tag = element_text(size=8),
          legend.position = "none")

## Modify plots
signature_paired_line <- signature_paired_line +
    geom_signif(aes(x = group,y = value),
                test = "wilcox.test",comparisons = list(c("diagnosis","relapse")),vjust = 1.4) +
    theme(legend.position = "none")

signature_stacked_alt <- signature_stacked_alt + theme(legend.position = "none")

## Get legends
sig_legend_a <- get_legend(
    signature_stacked_alt + 
        guides(fill = guide_legend(nrow = 1)) +
        theme(legend.position = "bottom")
)

sig_legend_b <- get_legend(
    signature_paired_line + 
        guides(fill = guide_legend(nrow = 1)) +
        theme(legend.position = "bottom")
)

## Figure 5 compile
fig5 <- plot_grid(plot_grid(signature_paired_line,
                  plot_grid(signature_stacked_alt,
                            radar_plot,
                            ncol = 2,labels = c("B","C")),
                  nrow = 2,
                  rel_heights = c(0.4,0.6,0.4),
                  labels = c("A","")),nrow = 2,
                  plot_grid(sig_legend_a,sig_legend_b,ncol = 2,labels = c("",""),scale = c(1,1.5)),
                  rel_heights = c(1,0.1))


## Figure 5 render
ggsave2(filename = "plots/figure_5_render.png",plot = fig5,width = 9,height = 10,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_5_render.pdf",plot = fig5,width = 9,height = 10,units = "in",dpi = 300)
fig5
```

```{r fig_6_patient_level}
# DOES NOT CURRENTLY RENDER DUE TO CORRELATION PLOT REQUIREMENTS

## Load plots
# focal_pairs_plot <- readRDS("copy_number_analysis/focal_analysis/plots/gene_pairs_plot.RDS")
# focal_heatmap_plot <- readRDS("copy_number_analysis/focal_analysis/plots/gene_change_heatmap.RDS")
# 
# ## Figure T1 compile
# fig6 <- plot_grid(focal_heatmap_plot,focal_pairs_plot,nrow = 2,labels = c("A","B"))
# 
# ## Figure T1 render
# ggsave2(filename = "plots/figure_6_render.png",plot = fig6,width = 8,height = 10,units = "in",dpi = 300)
# ggsave2(filename = "plots/figure_6_render.pdf",plot = fig6,width = 8,height = 10,units = "in",dpi = 300)
# fig6
```

```{r fig7_old}
## Load plots
# sig_bar_plot_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/sig_bar_plot_primary_pt_diag.RDS")
# sig_dist_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/sig_dist_primary_pt_diag.RDS")
# cn_focal_rate_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/primary_pt_rate_plot2.RDS")
# sig_primary_beta_results <- ggdraw() +
#                               draw_image(magick::image_read_pdf("../BriTROC-1-paired_analysis/results/partialILRmodelling_FE_other_regression/primary_platinum_resistant/betas_primaryplatinumsensitivity_partialILRnocor_partialILRnocor.pdf",density = 300))
# sig_primary_radar <- readRDS("plots/primary_resist_radar_partialILR_beta.RDS")
# sig_primary_radar <- sig_primary_radar +
#     labs(tag = "p=0.003, Wald test") +
#     theme(plot.tag.position = c(0.9, 0.1),
#           plot.tag = element_text(size=8),
#           legend.position = "none")
# 
# ## Modify plots
# sig_bar_plot_primary_pt_diag <- sig_bar_plot_primary_pt_diag +
#     theme(legend.position = "none")
# sig_dist_primary_pt_diag <- sig_dist_primary_pt_diag +
#     theme(legend.position = "none",axis.text.x = element_blank())
# #sig_dist_primary_pt_group_strat <- sig_dist_primary_pt_group_strat + theme(legend.position = "none",axis.text.x = element_blank())
# 
# ## Get legends
# sig_pt_primary_legend_a <- get_legend(
#   sig_bar_plot_primary_pt_diag + 
#     guides(fill = guide_legend(nrow = 1)) +
#     theme(legend.position = "bottom")
# )
# 
# sig_pt_primary_legend_b <- get_legend(
#   sig_dist_primary_pt_diag + 
#     guides(fill = guide_legend(nrow = 1)) +
#     theme(legend.position = "bottom")
# )
# ### Figure 7 compile
# fig7 <- plot_grid(plot_grid(cn_focal_rate_primary_pt_diag,
#                             sig_bar_plot_primary_pt_diag,
#                             sig_dist_primary_pt_diag,
#                             plot_grid(sig_primary_beta_results,
#                                       sig_primary_radar,
#                                       ncol = 2,labels = c("D","E")),
#                     labels = c("A","B","C",""),
#                     nrow = 4,
#                     rel_heights = c(1,1,0.6,1)),
#           plot_grid(empty,sig_pt_primary_legend_a,empty,sig_pt_primary_legend_b,
#                     nrow = 2,
#                     rel_widths = c(0.1,1,1)),
#           rel_heights = c(1.5,0.1),
#           nrow = 2)
# 
# ## Figure 7 render
# ggsave2(filename = "plots/figure_7_render.png",plot = fig7,width = 8,height = 12,units = "in",dpi = 300)
# ggsave2(filename = "plots/figure_7_render.pdf",plot = fig7,width = 8,height = 12,units = "in",dpi = 300)
# fig7
```

```{r fig7}
## Load plots
sig_bar_plot_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/sig_bar_plot_primary_pt_diag.RDS")
sig_dist_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/sig_dist_primary_pt_diag.RDS")
cn_focal_rate_primary_pt_diag <- readRDS("copy_number_analysis/focal_analysis/plots/primary_pt_rate_plot2.RDS")
sig_primary_beta_results <- ggdraw() +
    draw_image(magick::image_read_pdf("../BriTROC-1-paired_analysis/results/partialILRmodelling_FE_other_regression/primary_platinum_resistant/betas_primaryplatinumsensitivity_partialILRnocor_partialILRnocor.pdf",density = 300))
sig_primary_radar <- readRDS("plots/primary_resist_radar_partialILR_beta.RDS")
sig_primary_radar <- sig_primary_radar +
    labs(tag = "p=0.003, Wald test") +
    theme(plot.tag.position = c(0.85, 0.1),
          plot.tag = element_text(size=8),
          legend.position = "none")

## Modify plots
sig_bar_plot_primary_pt_diag <- sig_bar_plot_primary_pt_diag +
    facet_wrap(. ~ platinum_resistance,ncol = 1,scales = "free_x") +
    theme(legend.position = "none")
sig_dist_primary_pt_diag <- sig_dist_primary_pt_diag +
    theme(legend.position = "none",axis.text.x = element_blank())
#sig_dist_primary_pt_group_strat <- sig_dist_primary_pt_group_strat + theme(legend.position = "none",axis.text.x = element_blank())

## Get legends
sig_pt_primary_legend_a <- get_legend(
  sig_bar_plot_primary_pt_diag + 
    guides(fill = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

sig_pt_primary_legend_b <- get_legend(
  sig_dist_primary_pt_diag + 
    guides(fill = guide_legend(nrow = 1,
                               title = NULL)) +
    theme(legend.position = "bottom")
)
### Figure 7 compile
fig6 <- plot_grid(plot_grid(cn_focal_rate_primary_pt_diag,
                            #sig_dist_primary_pt_diag,
                            plot_grid(sig_bar_plot_primary_pt_diag,
                                      sig_primary_radar,
                                      ncol = 2,labels = c("B","C")),
                    labels = c("A"),
                    nrow = 2,
                    rel_heights = c(1,1,0.6,1)),
          plot_grid(empty,sig_pt_primary_legend_a,empty,sig_pt_primary_legend_b,
                    nrow = 2,
                    rel_widths = c(0.1,1,1)),
          rel_heights = c(1.5,0.1),
          nrow = 2)

## Figure 7 render
ggsave2(filename = "plots/figure_6_render.png",plot = fig6,width = 8,height = 10,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_6_render.pdf",plot = fig6,width = 8,height = 10,units = "in",dpi = 300)
fig6
```

```{r fig7}
## Rendered in sig_immune_analysis
```

```{r fig_pt_status}
## Load plots
sig_pt_bar_plot <- readRDS("copy_number_signatures/plots/sig_pt_bar_plot.RDS")
sig_pt_bar_plot <- sig_pt_bar_plot + theme(legend.position = "none")

sig_pt_plot <- readRDS("copy_number_signatures/plots/sig_pt_plot.RDS")
sig_pt_plot <- sig_pt_plot + theme(legend.position = "none")

sig_pt_plot_strat_group <- readRDS("copy_number_signatures/plots/sig_pt_plot_strat_group.RDS")
sig_pt_plot_strat_group <- sig_pt_plot_strat_group + theme(legend.position = "none")

sig_pt_legend_a <- get_legend(
  sig_pt_bar_plot + 
    guides(fill = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

sig_pt_legend_b <- get_legend(
  sig_pt_plot + 
    guides(fil = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

## Figure s## compile
fig6S <- plot_grid(plot_grid(sig_pt_bar_plot,sig_pt_plot,sig_pt_plot_strat_group,
                            labels = c("A","B","C"),
                            nrow = 3,
                            rel_heights = c(1,0.5,1)),
                  plot_grid(empty,sig_pt_legend_a,sig_pt_legend_b,
                            nrow = 1,
                            rel_widths = c(0.1,1,1)),
                  rel_heights = c(1.5,0.1),
                  nrow = 2)

## Plot render
ggsave2(filename = "plots/figure_6S_render.png",plot = fig6S,width = 8,height = 12,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_6S_render.pdf",plot = fig6S,width = 8,height = 12,units = "in",dpi = 300)
fig6S
```

```{r fig_tissue_diffs}
## Load plots
cna_tissue_rates <- readRDS("copy_number_analysis/sites_of_relapse/plots/cna_rates_tissue.RDS")
cna_tissue_counts <- readRDS("copy_number_analysis/sites_of_relapse/plots/cna_count_tissue.RDS")
cna_tissue_ith <- readRDS("copy_number_analysis/sites_of_relapse/plots/ith_tissue.RDS")
cna_tissue_sigs <- readRDS("copy_number_analysis/sites_of_relapse/plots/signature_tissue.RDS")

## Modify plots
cna_tissue_rates <- cna_tissue_rates +
                        theme(legend.position = "none",
                              axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5))

cna_tissue_counts <- cna_tissue_counts + theme(legend.position = "none",
                                               axis.ticks.x = element_blank(),
                                               axis.title.x = element_blank(),
                                               axis.text.x = element_blank())

cna_tissue_ith <- cna_tissue_ith + theme(legend.position = "none",
                                         axis.ticks.x = element_blank(),
                                         axis.title.x = element_blank(),
                                         axis.text.x = element_blank())

cna_tissue_sigs <- cna_tissue_sigs + theme(legend.position = "none",
                                           axis.ticks.x = element_blank(),
                                           axis.title.x = element_blank(),
                                           axis.text.x = element_blank()) 

## Get legends
tissue_legend_a <- get_legend(
  cna_tissue_counts + 
    guides(fill = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)
tissue_legend_b <- get_legend(
  cna_tissue_rates + 
    guides(fill = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

## Supplemental - tissue 1
tissue_supplemental1 <- plot_grid(plot_grid(plot_grid(cna_tissue_counts,labels = c("A",""),
                              plot_grid(cna_tissue_rates,cna_tissue_ith,labels = c("B","C"),
                                        ncol = 1,
                                        rel_heights = c(0.8,0.2))),
                                cna_tissue_sigs,labels = c("","D"),
                              nrow = 2,rel_heights = c(0.8,0.2)),
                              plot_grid(tissue_legend_b,tissue_legend_a),nrow = 2,labels = c("",""),rel_heights = c(1,0.1))

ggsave2(filename = "plots/tissue_supplemental1.png",plot = tissue_supplemental1,width = 10,height = 12,units = "in",dpi = 300)
ggsave2(filename = "plots/tissue_supplemental1.pdf",plot = tissue_supplemental1,width = 10,height = 12,units = "in",dpi = 300)
tissue_supplemental1
```

```{r fig_tissue_diffs_strat}
## Load supplemental tissue plots
cn_tissue_counts_strat <- readRDS("copy_number_analysis/sites_of_relapse/plots/cn_count_tissue_stratified.RDS")
cn_tissue_counts_strat <- cn_tissue_counts_strat + theme(legend.position = "none",axis.title.x = element_blank(),
                                                         axis.ticks.x = element_blank(),
                                                         axis.text.x = element_blank())
cn_tissue_sigs_strat <- readRDS("copy_number_analysis/sites_of_relapse/plots/cn_sigs_tissue_strat.RDS")
cn_tissue_sigs_strat <- cn_tissue_sigs_strat + theme(legend.position = "none",
                                                     axis.ticks.x = element_blank(),
                                                     axis.title.x = element_blank(),
                                                     axis.text.x = element_blank())
cn_tissue_ith_strat <- readRDS("copy_number_analysis/sites_of_relapse/plots/ith_tissue_strat.RDS")
cn_tissue_ith_strat <- cn_tissue_ith_strat + theme(legend.position = "none",
                                                   axis.ticks.x = element_blank(),
                                                   axis.title.x = element_blank(),
                                                   axis.text.x = element_blank())

tissue_legend_strat <- get_legend(
  cn_tissue_ith_strat + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

## Supplemental - tissue 2
tissue_supplemental2 <- plot_grid(plot_grid(cn_tissue_counts_strat,
                    plot_grid(cn_tissue_sigs_strat,cn_tissue_ith_strat,nrow = 2,labels = c("B","C")),
                    ncol = 2),
          tissue_legend_strat,
          labels = c("A",""),
          nrow = 2,
          rel_heights = c(1,0.1))

ggsave2(filename = "plots/tissue_supplemental2.png",plot = tissue_supplemental2,width = 10,height = 12,units = "in",dpi = 300)
ggsave2(filename = "plots/tissue_supplemental2.pdf",plot = tissue_supplemental2,width = 10,height = 12,units = "in",dpi = 300)
tissue_supplemental2
```

```{r fig_focal_rate_compare}
## Supplemental - TCGA-Britroc focal rate comparison 
britroc_tcga_comp_raw <- readRDS("copy_number_analysis/focal_analysis/plots/britroc_tcga_comp_raw.RDS")
britroc_tcga_comp_norm <- readRDS("copy_number_analysis/focal_analysis/plots/britroc_tcga_comp_norm.RDS")

## Modify plot
britroc_tcga_comp_raw <- britroc_tcga_comp_raw +
                            labs(title = "") +
                            theme(legend.position = "none")

britroc_tcga_comp_norm <- britroc_tcga_comp_norm +
                            labs(title = "") +
                            theme(legend.position = "bottom")

## Plot compile
sup_plot_britroc_tcga_rates <- plot_grid(britroc_tcga_comp_raw,britroc_tcga_comp_norm,nrow = 2,labels = c("A","B"))

## Plot render
ggsave2(filename = "plots/supplemental_figure_tcga_britroc_rates.png",plot = sup_plot_britroc_tcga_rates,width = 8,height = 8,units = "in",dpi = 300)
ggsave2(filename = "plots/supplemental_figure_tcga_britroc_rates.pdf",plot = sup_plot_britroc_tcga_rates,width = 8,height = 8,units = "in",dpi = 300)
sup_plot_britroc_tcga_rates
```

```{r misc}
sig_box_paired_wilcox <- readRDS("copy_number_signatures/plots/sig_box_paired_wilcox.RDS")
sig_box_paired_wilcox <- sig_box_paired_wilcox +
    labs(title = "",caption = "") + theme(legend.position = "none")
sig_box_paired_wilcox
```

```{r fig_ternary_combination,warning=F}
## List plots
pdf.list <- list.files(path = "copy_number_signatures/plots/ternary_all_combinations/",pattern = "ternary_all",full.names = TRUE)

highlight_list <- c("1+3+7","2+3+7","3+4+7","3+5+7","3+6+7")
## Load plots
plot.list <- lapply(pdf.list,FUN = function(x){
  name <- gsub(gsub(x = x,pattern = "copy_number_signatures/plots/ternary_all_combinations/ternary_all_",replacement = ""),
               pattern = ".pdf",replacement = "")
  #print(name)
  plot <- ggdraw() +
          draw_image(magick::image_read_pdf(x,density = 600))
  
  if(name %in% highlight_list){
        plot <- plot +
            theme(plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
                  plot.background = element_rect(color = "firebrick3",size = 3))
  } else {
        plot <- plot +
            theme(plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"))
  }
  return(plot)
})

## Plot compile
ternary_all <- plot_grid(plot_grid(plotlist = plot.list,nrow = 7,ncol = 5),
                sig_legend_b,nrow = 2,rel_heights = c(0.95,0.05))

## Plot render
ggsave2(filename = "plots/supplemental_figure_ternary_sig_plots_all.png",plot = ternary_all,width = 8,height = 12,units = "in",dpi = 300)
ggsave2(filename = "plots/supplemental_figure_ternary_sig_plots_all.pdf",plot = ternary_all,width = 8,height = 12,units = "in",dpi = 300)
ternary_all
```

```{r fig8}
## BRCA figure
diag_rlps_brca_rate_plot <- readRDS("copy_number_analysis/focal_analysis/plots/brca_diag_rlps_cna_rates_paired_plot.rds")
diag_rlps_brca_rate_plot <- diag_rlps_brca_rate_plot +
                            theme(axis.title.x = element_blank(),
                                  axis.text.x = element_blank(),
                                  axis.ticks.x = element_blank(),
                                  legend.position = "none")

brca_rate_plot <- readRDS("copy_number_analysis/focal_analysis/plots/brca_cna_rates_paired_plot.rds")
brca_rate_plot <- brca_rate_plot +
                    theme(legend.position = "none")

#brca_sig_bar <- readRDS("copy_number_analysis/focal_analysis/plots/brca_sig_bar_plot.rds")
brca_sig_copies <- readRDS("copy_number_analysis/focal_analysis/plots/brca_paired_amp_changes_plot.rds")
brca_sig_copies <- brca_sig_copies +
                            theme(axis.title.x = element_blank(),
                                  axis.text.x = element_blank(),
                                  axis.ticks.x = element_blank(),
                                  legend.position = "none")

brca_sig_radar <- readRDS("plots/brca_status_radar_partialILR_beta.RDS")
brca_sig_radar <- brca_sig_radar +
                    theme(legend.position = "none")

brca_sig_radar <- brca_sig_radar +
    labs(tag = "p=0.25, Wald test") +
    theme(plot.tag.position = c(0.85, 0.1),
          plot.tag = element_text(size=8),
          legend.position = "none")

diag_legend <- get_legend(
  diag_rlps_brca_rate_plot + 
    guides(fill = guide_legend(title = "group",nrow = 1)) +
    theme(legend.position = "bottom")
)

brca_legend <- get_legend(
  brca_rate_plot + 
    guides(fill = guide_legend(title = "BRCA status",nrow = 1)) +
    theme(legend.position = "bottom")
)

fig8 <- plot_grid(diag_rlps_brca_rate_plot,
          brca_rate_plot,
          plot_grid(brca_sig_copies,brca_sig_radar,
                    ncol = 2,labels=c("C","D")),
          plot_grid(empty,diag_legend,brca_legend,empty,
                    rel_widths = c(0.1,0.25,0.30,0.05),ncol = 4),
          labels=c("A","B","",""),
          nrow = 4,
          rel_heights = c(0.20,0.20,0.40,0.04))

ggsave2(filename = "plots/figure_8_render.png",plot = fig8,width = 8,height = 11,units = "in",dpi = 300)
ggsave2(filename = "plots/figure_8_render.pdf",plot = fig8,width = 8,height = 11,units = "in",dpi = 300)
fig8
```

```{r session_info}
sessionInfo()
```
