---
title: "Medicc2 britroc analysis"
author: "Philip Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
library(data.table)
library(GenomicRanges)
library(tidyverse)
library(ggplotify)
library(ape)
```

```{r funcs}
source("data/medicc2_analysis_funcs.R")
```

```{r vars}
binsize <- 30000
```

```{r load_medicc_data}
all.trees <- read.tree("data/medicc2_output/all.trees.new")

all.profiles <- read_profiles(dir = "data/medicc2_output/")

all.profiles <- modify_profiles(profiles = all.profiles)

seqlengths <- get_seq_lengths(x = all.profiles)

all.profiles.binned <- bin_profiles(all.profiles)
```

```{r read_meta_clin}
meta.data <- read.table("../../copy_number_signatures/britroc_30kb_signature_data_meta.tsv",header = T,sep = "\t")
clin.data <- read.table("../../britroc_cohort_patient_data.tsv",header = T,sep = "\t")

primary.samples <- meta.data$SAMPLE_ID[meta.data$group == "arx"]
relapse.samples <- meta.data$SAMPLE_ID[meta.data$group == "rlps"]
```

```{r name_and_plot_trees}
all.trees <- name_trees(all.trees)
plot(all.trees[[1]])
```

```{r tree_stats}
## Extract series of tree statistics
tree_stats <- get_tree_stats(all.trees)
## Add sample information
tree_stats <- add_sample_info(tree_stats)
## Add BRITROC ID back
tree_stats <- tree_stats %>%
                mutate(PATIENT_ID = str_split(string = SET_ID,pattern = "_",n = 3,simplify = T)[,1]) %>%
                relocate(PATIENT_ID,SET_ID,paired,primary_only,relapse_only,sample_types)
```

```{r add_clin_data}
tree_stats <- add_clin_data(table = tree_stats,clin = c("pt_sensitivity_at_reg","age","os","pfs","tumour_stage_at_diagnosis","pre_reg_chemo"))
tree_stats$tumour_stage_at_diagnosis <- as.factor(tree_stats$tumour_stage_at_diagnosis)

head(tree_stats)
```

```{r profile_annotations}
fork_profiles <- all.profiles.binned[tree_stats$PATIENT_ID[tree_stats$paired == "TRUE" & tree_stats$nsamples == 3]]
fork_profiles_ann <- annotate_profile_segments(profiles = fork_profiles)

## segment id plot example
plot_segment_identities(x = fork_profiles_ann[[1]])
#ggsave(plot = p,filename = "plots/patient_tree_segIds_example.png",width = 8,height = 4,units = "in",dpi = 300)
## summarise segment.ids

segment.id.summary <- do.call(rbind,lapply(names(fork_profiles_ann),FUN = function(x){
  y <- fork_profiles_ann[[x]]
  t <- data.frame(patient=x,table(y$segment.id))
}))

ggplot(segment.id.summary) +
  geom_boxplot(aes(Var1,Freq,fill=Var1)) +
  coord_flip() +
  theme_bw()
```

```{r internal_arx_subtraction}

### BINS NEED TO BE EQUAL ACROSS ALL PATIENTS

do.call(rbind,lapply(fork_profiles_ann[1],FUN = function(x){
  col.names <- colnames(x)
  primary.col <- which(col.names %in% primary.samples)
  relapse.col <- which(col.names %in% relapse.samples)
  diploid.col <- which(col.names == "diploid")
  internal.col <- which(col.names == "internal_1")
  x <- x %>%
    mutate(internal_relapse_events = as.numeric(.[[relapse.col]] - .[[internal.col]])) %>%
    dplyr::select(internal_relapse_events)
  return(x)
}))

# get_internal_genome_diffs <- function(data,method="median"){
#   patients <- names(data)
#   
#   arx_int <- do.call(cbind,lapply(patients,FUN = function(x){
#     pat_name <- x
#     mat <- data[[pat_name]]
#     abs_subset <- mat[,colnames(mat) %in% primary.samples]
#     if(method == "mean"){
#       arx_bin <- rowMeans(abs_arx_bins,na.rm = T)
#     } else if(method == "median"){
#       arx_bin <- rowMedians(abs_arx_bins,na.rm = T)
#     } else {
#       stop("unknown method")
#     }
#     return(arx_bin)
#   }))
#     
#   })
#   arxdiffs <- do.call(cbind,lapply(names(sample_by_pat_list),FUN = function(x){
#     pat_name <- x
#     abs_samples <- sub_meta$SAMPLE_ID[sub_meta$PATIENT_ID %in% x]
#     abs_subset <- data[,colnames(data) %in% abs_samples]
#     arx_samps <- colnames(abs_subset)[colnames(abs_subset) %in% arx_samples]
#     abs_arx <- abs_subset[,colnames(abs_subset) %in% arx_samps]
#     abs_arx_bins <- assayDataElement(abs_arx,elt = "segmented")
#     if(method == "mean"){
#       arx_bin <- rowMeans(abs_arx_bins,na.rm = T)
#     } else if(method == "median"){
#       arx_bin <- rowMedians(abs_arx_bins,na.rm = T)
#     } else {
#       stop("unknown method")
#     }
#     return(arx_bin)
#   }))
#   
#   rlpsdiffs <- do.call(cbind,lapply(names(sample_by_pat_list),FUN = function(x){
#     pat_name <- x
#     abs_samples <- sub_meta$SAMPLE_ID[sub_meta$PATIENT_ID %in% x]
#     abs_subset <- data[,colnames(data) %in% abs_samples]
#     rlps_samps <- colnames(abs_subset)[colnames(abs_subset) %in% rlps_samples]
#     abs_rlps <- abs_subset[,colnames(abs_subset) %in% rlps_samps]
#     abs_rlps_bins <- assayDataElement(abs_rlps,elt = "segmented")
#     
#     if(method == "mean"){
#       rlps_bin <- rowMeans(abs_rlps_bins,na.rm = T)
#     } else if(method == "median"){
#       rlps_bin <- rowMedians(abs_rlps_bins,na.rm = T)
#     } else {
#       stop("unknown method")
#     }
#     return(rlps_bin)
#   }))
#   arxdiffs <- data.frame(arxdiffs)
#   colnames(arxdiffs) <- paste0(names(sample_by_pat_list),"_arx")
# 
#   rlpsdiffs <- data.frame(rlpsdiffs) 
#   colnames(rlpsdiffs) <- paste0(names(sample_by_pat_list),"_rlps")
#   
#   diffs <- cbind(arxdiffs,rlpsdiffs)
#   rownames(diffs) <- rownames(data)
#   return(diffs)
# }
# 
# paired_diffs <- get_paired_genome_diffs(data = abs_data[,colnames(abs_data) %in% meta.data$SAMPLE_ID[meta.data$paired == "TRUE"]],
#                                         method = "median")
```

```{r plot_format}
tree_stats_long <- tree_stats %>%
                    pivot_longer(cols = c(7:15),names_to = "tree", values_to = "n")

patient_treelen_order <- tree_stats_long[tree_stats_long$tree == "tree.length",] %>%
  arrange(n) %>%
  dplyr::select(SET_ID)
tree_stats_long$SET_ID <- factor(tree_stats_long$SET_ID,levels = patient_treelen_order$SET_ID)
```

```{r tree_plots}
ggplot(tree_stats_long[tree_stats_long$tree == "tree.length",]) +
  geom_boxplot(aes(sample_types,n,fill=sample_types)) +
  theme_bw() +
  coord_flip()

# ggplot(tree_stats_long) +
#   geom_point(aes(chemotherapy_lines,n,colour=chemotherapy_lines),position="jitter") +
#   geom_boxplot(aes(chemotherapy_lines,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw()

# ggplot(tree_stats_long) +
#   geom_point(aes(pt_sensitivity_at_reg,n,colour=pt_sensitivity_at_reg),position="jitter") +
#   geom_boxplot(aes(pt_sensitivity_at_reg,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw()
# 
# ggplot(tree_stats_long) +
#   geom_point(aes(tumour_stage_at_diagnosis,n,colour=tumour_stage_at_diagnosis),position="jitter") +
#   geom_boxplot(aes(tumour_stage_at_diagnosis,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw() +
#   theme(legend.position = "bottom")
# 
# ggplot(tree_stats_long) +
#   geom_point(aes(os,n,colour=os)) +
#   #geom_boxplot(aes(os,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw() +
#   theme(legend.position = "bottom")
# 
# ggplot(tree_stats_long) +
#   geom_point(aes(pfs,n,colour=pfs)) +
#   #geom_boxplot(aes(pfs,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw() +
#   theme(legend.position = "bottom")
# 
# ggplot(tree_stats_long) +
#   geom_point(aes(tree,n,colour=tree),position="jitter") +
#   geom_boxplot(aes(tree,n),fill=NA,outlier.colour = NA) +
#   #facet_wrap(.~tree,scales = "free") +
#   theme_bw()
# 
# ggplot(tree_stats_long) +
#   geom_point(aes(n,PATIENT_ID,colour=tree),position="jitter") +
#   #geom_boxplot(aes(tree,n),fill=NA,outlier.colour = NA) +
#   facet_wrap(.~tree,scales = "free") +
#   theme_bw() +
#   theme(legend.position = "bottom",axis.text.y = element_blank())
```

