---
title: "BriTROC 30kb copy number signature analysis"
author: "Philip Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

## Intial setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries

```{r library_load, warning=FALSE}
# Load required libraries with supressed start-up text
suppressMessages(library(QDNAseqmod))
suppressMessages(library(tidyverse))
suppressMessages(library(kableExtra))
suppressMessages(library(ggplot2))
suppressMessages(library(reshape2))
suppressMessages(library(Biobase))
suppressMessages(library(cowplot))
suppressMessages(library(RColorBrewer))
suppressMessages(library(plotly))
suppressMessages(library(ggsignif))
```

### Source functions

```{r source_scripts}
# Load main functions
source("data/britroc_30kb_functions.R")
source("../colour_palettes.R")
```

### Load sig data

```{r meta.data}
# Load abs cn meta data and add arx/rlps annotation based on sample name prefix
load("britroc_30kb_signature_data.Rdata")
# Factor of samples in patient order for exposure plots etc
patient_sorted_samples <- factor(patient.meta$SAMPLE_ID[order(patient.meta$PATIENT_ID)],
                                 levels = unique(patient.meta$SAMPLE_ID[order(patient.meta$PATIENT_ID)]))
patient.data <- read.table("../britroc_cohort_patient_data.tsv",header = TRUE,sep = "\t")

im_list <- read.table("../britroc_primary_platinum_resistant_patient_list.tsv",header = T,sep = "\t")
```

### Load abs data

```{r load_abs}
abs_data <- readRDS("../absolute_POST_down_sampling/britroc_30kb_ds_absCopyNumber.rds")
abcel_abs <- readRDS("../absolute_PRE_down_sampling/abcel_absoluteCN_30kbps_refitted.rds")
```

### Load external data

```{r ext}
## file check due to long computation time
if(file.exists("data/tcga_CN_sample_comp.rds")){
  tcga_samp_comp <- readRDS("data/tcga_CN_sample_comp.rds")
} else {
  tcga_samp_comp <- generateSampleByComponentMatrix(readRDS("data/tcga_CN_features.rds"))
  saveRDS(tcga_samp_comp,file = "data/tcga_CN_sample_comp.rds")
}
tcga_sigs <- quantifySignatures(tcga_samp_comp)

if(file.exists("data/pcawg_CN_sample_comp.rds")){
  pcawg_samp_comp <- readRDS("data/pcawg_CN_sample_comp.rds")
} else {
  pcawg_samp_comp <- generateSampleByComponentMatrix(readRDS("data/pcawg_CN_features.rds"))
  saveRDS(pcawg_samp_comp,file = "data/pcawg_CN_sample_comp.rds")
}
pcawg_sigs <- quantifySignatures(pcawg_samp_comp)

if(file.exists("data/natgen_CN_sample_comp.rds")){
  natgen_samp_comp <- readRDS("data/natgen_CN_sample_comp.rds")
} else {
  natgen_samp_comp <- generateSampleByComponentMatrix(readRDS("data/natgen_CN_features.rds"))
  saveRDS(natgen_samp_comp,file = "data/natgen_CN_sample_comp.rds")
}
natgen_sigs <- quantifySignatures(natgen_samp_comp)
```

```{r feat_dists}
samp_comp_long <- as.data.frame(sample_by_component) %>%
  rownames_to_column(var="sample") %>%
  pivot_longer(cols = 2:ncol(.)) %>%
  mutate(feat = gsub(pattern = "[0-9]+|[1-9][0-9]$",replacement = "",perl = T,x = name)) %>%
  mutate(feat = gsub(pattern = "bpMB",replacement = "bp10MB",x = feat)) %>%
  mutate(cohort = rep("britroc",times= length(feat))) %>%
  mutate(group = patient.meta$group[match(sample,patient.meta$SAMPLE_ID)]) %>%
  mutate(group = case_when(group == "arx" ~ "diagnosis",group == "rlps" ~ "relapse"))

samp_comp_long$name <- factor(samp_comp_long$name,levels = rev(stringr::str_sort(unique(samp_comp_long$name),numeric = T,decreasing = T)))
head(samp_comp_long)
```

```{r feat_dist_plot}
seq <- c()
for(i in sort(unique(samp_comp_long$feat))){
  p <- seq.int(1,length(unique(samp_comp_long$name[samp_comp_long$feat == i])),1)
  seq <- append(seq,p)
}

ggplot(samp_comp_long,aes(x = value)) +
  geom_density(aes(color=group)) +
  facet_wrap(. ~ name,scales = "free") +
  scale_x_discrete(labels = seq) +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())

feat_plot <- ggplot(samp_comp_long) +
  geom_jitter(aes(x = group,y = value),alpha = 0.2) +
  geom_violin(aes(x = group,y = value,fill = group),alpha = 0.5) +
  facet_wrap(. ~ name,scales = "free_y") +
  geom_signif(aes(x = group,y = value),
              comparisons = list(c("diagnosis","relapse")),
              test = "wilcox.test",vjust = 1.2) +
  xlab("") +
  ylab("") +
  scale_fill_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 90,hjust = 0.5))

saveRDS(object = feat_plot,file = "plots/feat_plot.RDS")
ggsave(feat_plot,filename = "plots/feat_plot.png",width = 8,height = 8,units = "in",dpi = 300)
ggsave(feat_plot,filename = "plots/feat_plot.pdf",width = 8,height = 8,units = "in",dpi = 300)
feat_plot
```

## Signature proportions

```{r patient_ordering}
t.sig_quants <- t(sig_quants)
sample_order <- rownames(t.sig_quants[order(t.sig_quants[,1],t.sig_quants[,2],t.sig_quants[,3],
                                            t.sig_quants[,4],t.sig_quants[,5],t.sig_quants[,6],decreasing = T),])
```

```{r sak_data_request}
# request_sample_list <- read.table("../../data_requests/TEMP_SarwahBriTROC_IDs_request.csv",header = T,sep = ",")
# sig_request_table <- sig_quants[,colnames(sig_quants) %in% request_sample_list$ID]
# write.table(t(sig_request_table),file = "../data_requests/cn_signatures_dataRequest_SAK.tsv",quote = F,sep = "\t",row.names = T,col.names = T)
```

### Bar plot

```{r bar_plot}
sig_bar <- as.data.frame(sig_quants) %>%
  rownames_to_column(var = "signature") %>%
  pivot_longer(cols = -1,names_to="SAMPLE_ID") %>%
  left_join(y = patient.meta,by = "SAMPLE_ID") %>%
  #filter(paired == TRUE) %>%
  dplyr::select(-c(ploidy,purity,TP53cn,expected_TP53_AF,TP53freq,use,notes,paired)) #%>%
  # group_by(signature,group) %>%
  # summarise(across(value,.fns = mean))
  
#sig_bar$SAMPLE_ID <- factor(sig_bar$SAMPLE_ID,levels = unique(sig_bar$SAMPLE_ID[order(sig_bar$value,sig_bar$signature,decreasing = T)]))
sig_bar$SAMPLE_ID <- factor(sig_bar$SAMPLE_ID,levels = sample_order)

sig_bar_plot <- ggplot(sig_bar) +
  geom_col(aes(SAMPLE_ID,value,fill=signature)) +
  facet_wrap(. ~ group,nrow = 2,
             labeller = labeller(group = c(arx="diagnosis",rlps="relapse")),scales = "free_x") +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  ylab("exposure") +
  xlab("sample") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

saveRDS(object = sig_bar_plot,file = "plots/signatures_allSamples_stacked_bar.RDS")
ggsave(sig_bar_plot,filename = "plots/signatures_allSamples_stacked_bar.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(sig_bar_plot,filename = "plots/signatures_allSamples_stacked_bar.pdf",width = 8,height = 6,units = "in",dpi = 300)
sig_bar_plot
```

```{r bar_plot_paired_data}
sig_bar_paired <- as.data.frame(sig_quants) %>%
  rownames_to_column(var = "signature") %>%
  pivot_longer(cols = -1,names_to="SAMPLE_ID") %>%
  left_join(y = patient.meta,by = "SAMPLE_ID") %>%
  filter(paired == TRUE) %>%
  dplyr::select(-c(ploidy,purity,TP53cn,expected_TP53_AF,TP53freq,use,notes,paired)) %>%
  group_by(PATIENT_ID,signature,group) %>%
  summarise(across(value,.fns = median)) %>%
  # renormalise data to one after taking median
  ungroup() %>%
  group_by(PATIENT_ID,group) %>%
  mutate(value = value / sum(value))

# sig_bar_paired$PATIENT_ID <- factor(sig_bar_paired$PATIENT_ID,
#                              levels = unique(sig_bar_paired$PATIENT_ID[order(sig_bar_paired$value,sig_bar_paired$signature,decreasing = T)]))

pat_ordering <- pivot_wider(sig_bar_paired[sig_bar_paired$group == "arx",],id_cols = "PATIENT_ID",names_from = "signature",values_from = "value") %>%
                  column_to_rownames("PATIENT_ID")
patient_order <- rownames(pat_ordering[order(pat_ordering[,1],pat_ordering[,2],pat_ordering[,3],
                                             pat_ordering[,4],pat_ordering[,5],pat_ordering[,6],decreasing = T),])

sig_bar_paired$PATIENT_ID <- factor(sig_bar_paired$PATIENT_ID,
                             levels = patient_order)
```

```{r temp_data_request}
# temp data request IM
# write.table(x = sig_bar_paired,
#             file = "../data requests/britroc_patient_signatures_medianNorm_IM.tsv",
#             quote = F,sep = "\t",row.names = F,col.names = T)
# sig_bar_paired_wide <- sig_bar_paired %>%
#                         pivot_wider(names_from = "signature",values_from = "value")
```

```{r bar_plot_paired_plots}
sig_bar_plot_paired <- ggplot(sig_bar_paired) +
  geom_col(aes(PATIENT_ID,value,fill=signature)) +
  facet_wrap(. ~ group,nrow = 2,labeller = labeller(group = c(arx="diagnosis",rlps="relapse"))) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  ylab("exposure") +
  xlab("patient") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

saveRDS(object = sig_bar_plot_paired,file = "plots/signatures_stacked_bar.RDS")
ggsave(sig_bar_plot_paired,filename = "plots/signatures_stacked_bar.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(sig_bar_plot_paired,filename = "plots/signatures_stacked_bar.pdf",width = 8,height = 6,units = "in",dpi = 300)
sig_bar_plot_paired

sig_bar_paired_alt <- sig_bar_paired %>%
                        mutate(value = ifelse(group == "arx",-value,value))

sig_bar_paired_alt$PATIENT_ID <- factor(sig_bar_paired_alt$PATIENT_ID,levels = rev(levels(sig_bar_paired_alt$PATIENT_ID)))

sig_bar_plot_paired_alt <- ggplot(sig_bar_paired_alt) +
  geom_col(aes(PATIENT_ID,value,fill=signature),position = position_stack(reverse = TRUE)) +
  #facet_wrap(. ~ group,nrow = 2,labeller = labeller(group = c(arx="diagnosis",rlps="relapse"))) +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = cbPalette) +
  scale_y_continuous(labels = c(1.0,0.5,0.0,0.5,1.0),expand = c(0,0)) +
  ylab("exposure") +
  xlab("patient") +
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right") +
  annotate(geom = "text",x = 48.4,y = c(-0.85,0.88),label = c("diagnosis","relapse")) +
  coord_flip(clip = "off",xlim = c(1,47)) +
  theme(plot.margin = unit(c(1,1,1,1),units = "line"))

saveRDS(object = sig_bar_plot_paired_alt,file = "plots/signatures_stacked_bar_alt.RDS")
ggsave(sig_bar_plot_paired_alt,filename = "plots/signatures_stacked_bar_alt.png",width = 6,height = 8,units = "in",dpi = 300)
ggsave(sig_bar_plot_paired_alt,filename = "plots/signatures_stacked_bar_alt.pdf",width = 6,height = 8,units = "in",dpi = 300)
sig_bar_plot_paired_alt
```

### Pt status and prior lines

```{r pt_status_sig}
sig_bar$pt_status <- patient.data$pt_sensitivity_at_reg[match(sig_bar$PATIENT_ID,paste0("BRITROC-",patient.data$britroc_number))]
sig_bar$prior_lines <- patient.data$pre_reg_chemo[match(sig_bar$PATIENT_ID,paste0("BRITROC-",patient.data$britroc_number))]

sig_bar_filt <- sig_bar %>%
                  filter(!is.na(pt_status) & !is.na(prior_lines)) %>%
                  mutate(group = case_when(group == "arx" ~ "diagnosis",group == "rlps" ~ "relapse"))
                  

sig_pt_bar_plot <- ggplot(sig_bar_filt) +
  geom_col(aes(SAMPLE_ID,value,fill=signature)) +
  facet_wrap(group ~ pt_status,
             scales = "free_x") +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  ylab("exposure") +
  xlab("sample") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

sig_pt_plot <- ggplot(data = sig_bar_filt) +
    geom_boxplot(aes(x = pt_status,y = value,fill=pt_status)) +
    geom_signif(aes(x = pt_status,y = value),
                test = "wilcox.test",comparisons = list(c("resistant","sensitive")),vjust = 1.3) +
    facet_wrap(. ~ signature,scales = "free_x",nrow = 1) +
    scale_fill_manual(values = colour_palettes$resist_sensitive) +
    theme_bw() +
    theme(legend.position = "bottom")

sig_pt_plot_strat_group <- ggplot(data = sig_bar_filt) +
    geom_boxplot(aes(x = pt_status,y = value,fill=pt_status)) +
    geom_signif(aes(x = pt_status,y = value),
                test = "wilcox.test",comparisons = list(c("resistant","sensitive")),vjust = 1.3) +
    facet_wrap(group ~ signature,scales = "free_x",nrow = 2) +
    scale_fill_manual(values = colour_palettes$resist_sensitive) +
    theme_bw() +
    theme(legend.position = "bottom")

sig_group_strat_pt <- ggplot(data = sig_bar_filt) +
    geom_boxplot(aes(x = group,y = value,fill=group)) +
    geom_signif(aes(x = group,y = value),
                test = "wilcox.test",comparisons = list(c("diagnosis","relapse")),vjust = 1.3) +
    facet_wrap(pt_status ~ signature,scales = "free_x",nrow = 2) +
    scale_fill_manual(values = colour_palettes$diagnosis_relapse) +
    theme_bw() +
    theme(legend.position = "bottom")

saveRDS(object = sig_pt_bar_plot,file = "plots/sig_pt_bar_plot.RDS")
ggsave(sig_pt_bar_plot,filename = "plots/sig_pt_bar_plot.png",width = 9,height = 6,units = "in",dpi = 300)
ggsave(sig_pt_bar_plot,filename = "plots/sig_pt_bar_plot.pdf",width = 9,height = 6,units = "in",dpi = 300)
sig_pt_bar_plot

saveRDS(object = sig_pt_plot,file = "plots/sig_pt_plot.RDS")
ggsave(sig_pt_plot,filename = "plots/sig_pt_plot.png",width = 9,height = 6,units = "in",dpi = 300)
ggsave(sig_pt_plot,filename = "plots/sig_pt_plot.pdf",width = 9,height = 6,units = "in",dpi = 300)
sig_pt_plot

saveRDS(object = sig_pt_plot_strat_group,file = "plots/sig_pt_plot_strat_group.RDS")
ggsave(sig_pt_plot_strat_group,filename = "plots/sig_pt_plot_strat_group.png",width = 9,height = 6,units = "in",dpi = 300)
ggsave(sig_pt_plot_strat_group,filename = "plots/sig_pt_plot_strat_group.pdf",width = 9,height = 6,units = "in",dpi = 300)
sig_pt_plot_strat_group

saveRDS(object = sig_group_strat_pt,file = "plots/sig_group_strat_pt.RDS")
ggsave(sig_group_strat_pt,filename = "plots/sig_group_strat_pt.png",width = 9,height = 6,units = "in",dpi = 300)
ggsave(sig_group_strat_pt,filename = "plots/sig_group_strat_pt.pdf",width = 9,height = 6,units = "in",dpi = 300)
sig_group_strat_pt
```

```{r pt_status_im_list}
sig_bar_filt$pt_status_new <- ifelse(gsub(sig_bar_filt$PATIENT_ID,
                                          pattern = "BRITROC-",replacement = "") %in% im_list$PATIENT_ID,"im_list",as.character(sig_bar_filt$pt_status))


ggplot(data = sig_bar_filt) +
    geom_boxplot(aes(x = pt_status_new,y = value,fill=pt_status_new)) +
    geom_signif(aes(x = pt_status_new,y = value),
                test = "wilcox.test",comparisons = list(c("resistant","sensitive"),
                                                        c("resistant","im_list"),
                                                        c("im_list","sensitive")),
                vjust = 1.3,
                y_position = c(0.85,0.75,0.95)) +
    facet_wrap(group ~ signature,scales = "free_x",nrow = 2) +
    theme_bw() +
    theme(legend.position = "bottom")
```

```{r prior_lines_sig}
ggplot(sig_bar_filt[sig_bar_filt$prior_lines < 5,]) +
  geom_col(aes(SAMPLE_ID,value,fill=signature)) +
  facet_wrap(group ~ prior_lines,
             scales = "free_x") +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  ylab("exposure") +
  xlab("sample") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")

ggplot(data = sig_bar_filt[sig_bar_filt$prior_lines < 5,]) +
    geom_boxplot(aes(x = as.factor(prior_lines),y = value,fill=as.factor(prior_lines))) +
    geom_signif(aes(x = as.factor(prior_lines),y = value),
                test = "wilcox.test",comparisons = list(c("1","2")),vjust = 1.2) +
    facet_wrap(. ~ signature,scales = "free_x",nrow = 2) +
    scale_fill_manual(values = colour_palettes$prior_lines) +
    theme_bw()

ggplot(data = sig_bar_filt[sig_bar_filt$prior_lines < 5,]) +
    geom_boxplot(aes(x = as.factor(prior_lines),y = value,fill=as.factor(prior_lines))) +
    facet_grid(rows = vars(group),cols = vars(signature),scales = "free_x") +
    scale_fill_manual(values = colour_palettes$prior_lines) +
    theme_bw()

ggplot(data = sig_bar_filt[sig_bar_filt$prior_lines < 5,]) +
    geom_boxplot(aes(x = group,y = value,fill=group)) +
    geom_signif(aes(x = group,y = value),
                test = "wilcox.test",comparisons = list(c("diagnosis","relapse")),vjust = 1.2) +
    facet_grid(rows = vars(as.factor(prior_lines)),cols = vars(signature),scales = "free_x") +
    scale_fill_manual(values = colour_palettes$diagnosis_relapse) +
    theme_bw()
```

### All samples

```{r sig_box_plot}
sig_box_wilcox <- sig_box_plot(sig_quants = sig_quants,
             plot_title = "Signature exposures between tumour groups (all-mann.whitney)",
             test = "wilcox.test")

sig_box_wilcox

saveRDS(object = sig_box_wilcox,file = "plots/sig_box_wilcox.RDS")
ggsave(sig_bar_plot,filename = "plots/sig_box_wilcox.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(sig_bar_plot,filename = "plots/sig_box_wilcox.pdf",width = 8,height = 6,units = "in",dpi = 300)
```

### Paired samples

```{r sig_box_plot_pair}
sig_box_paired_wilcox <- sig_box_plot(sig_quants = sig_quants[,colnames(sig_quants) %in% patient.meta$SAMPLE_ID[patient.meta$paired == TRUE]],
             test = "wilcox.test",paired = TRUE,
             plot_title = "Signature exposures between tumour groups (paired-wilcoxon)")
sig_box_paired_wilcox

saveRDS(object = sig_box_paired_wilcox,file = "plots/sig_box_paired_wilcox.RDS")
ggsave(sig_bar_plot,filename = "plots/sig_box_paired_wilcox.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(sig_bar_plot,filename = "plots/sig_box_paired_wilcox.pdf",width = 8,height = 6,units = "in",dpi = 300)
```

```{r sig_paired_line_plot}
paired_line <- sig_box_paired_wilcox$data
paired_line_plot <- ggplot(paired_line) +
  geom_line(aes(group,value,group=PATIENT_ID),alpha=0.3) +
  geom_point(aes(group,value,color=group)) +
  facet_wrap(. ~ Signature,nrow = 1) +
  scale_y_continuous(limits = c(0,1)) +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  xlab("signature") +
  ylab("exposure") +
  theme_bw() +
  theme(legend.position = "bottom",axis.text.x = element_blank(),axis.ticks.x = element_blank())

saveRDS(object = paired_line_plot,file = "plots/paired_line_plot.RDS")
ggsave(paired_line_plot,filename = "plots/paired_line_plot.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(paired_line_plot,filename = "plots/paired_line_plot.pdf",width = 8,height = 6,units = "in",dpi = 300)
paired_line_plot
```

### Comparison to TCGA/PCAWG

```{r sig_box_plot_compare}
sig_box_data <- rownames_to_column(as.data.frame(t(sig_quants)),var = "Sample")
sig_box_data$group <- rep("britroc",times=nrow(sig_box_data))

natgen_box_data <- rownames_to_column(as.data.frame(t(natgen_sigs)),var = "Sample")
natgen_box_data$group <- rep("natgen",times=nrow(natgen_box_data))

tcga_box_data <- rownames_to_column(as.data.frame(t(tcga_sigs)),var = "Sample")
tcga_box_data$group <- rep("tcga",times=nrow(tcga_box_data))

pcawg_box_data <- rownames_to_column(as.data.frame(t(pcawg_sigs)),var = "Sample")
pcawg_box_data$group <- rep("pcawg",times=nrow(pcawg_box_data))

x <- pivot_longer(data = rbind(sig_box_data,natgen_box_data,tcga_box_data,pcawg_box_data),cols = c(2:8),names_to = "Signature")

sig_box_plot_compare_plot <- ggplot(data = x) +
    geom_boxplot(aes(x = Signature,y = value,fill=group)) +
    labs(title = "Signature exposures by signature between cohorts") +
    scale_y_continuous(name = "Exposure",limits = c(0,1)) +
    theme_bw()

ggsave(sig_box_plot_compare_plot,filename = "plots/sig_box_plot_compare_plot.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(sig_box_plot_compare_plot,filename = "plots/sig_box_plot_compare_plot.pdf",width = 8,height = 6,units = "in",dpi = 300)
sig_box_plot_compare_plot
```

### Signature corr.

```{r signature_corr}
subset_natgen <- as.data.frame(t(natgen_sigs[,colnames(natgen_sigs) %in% patient.meta$SAMPLE_ID]))
subset_sig_quants <- as.data.frame(t(sig_quants[,colnames(sig_quants) %in% rownames(subset_natgen)]))

subset_natgen <- rownames_to_column(subset_natgen) 
subset_natgen <- pivot_longer(subset_natgen,cols = 2:8)
subset_natgen$group <- rep("natgen",times=nrow(subset_natgen))

subset_sig_quants <- rownames_to_column(subset_sig_quants) 
subset_sig_quants <- pivot_longer(subset_sig_quants,cols = 2:8)
subset_sig_quants$group <- rep("britroc",times=nrow(subset_sig_quants))

subset_sig_quants$natgen_value <- subset_natgen$value

pearson.c <- c()
pearson.p <- c()
for(i in unique(subset_sig_quants$name)){
  s <- subset_sig_quants[subset_sig_quants$name == i,]
  pearson.c <- append(pearson.c,cor.test(x = s$value,y=s$natgen_value,method = "pearson")$estimate)
  pearson.p <- append(pearson.p,cor.test(x = s$value,y=s$natgen_value,method = "pearson")$p.value)
}
corr.data <- rbind(round(pearson.c,digits = 2),formatC(pearson.p, format = "e", digits = 2))
colnames(corr.data) <- unique(subset_sig_quants$name)
rownames(corr.data) <- c("corr","p.value")
kable(corr.data)
```

```{r external_corr_plot}
corr.data.t <- as.data.frame(t(corr.data))
corr.data.t <- rownames_to_column(corr.data.t,var = "name")

external_corr_plot <- ggplot(subset_sig_quants) + geom_point(aes(x = value,y = natgen_value)) +
  stat_smooth(aes(x = value,y = natgen_value),method = "lm") +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_continuous(limits = c(0,1)) +
  labs(title = "Signature correlations - Natgen vs new") +
  xlab("BriTROC relative exposure") +
  ylab("Natgen relative exposure") +
  facet_wrap(. ~ name) +
  geom_text(data = corr.data.t,aes(label=paste0("cor=",corr)),
            x = 0.9,y = 0.9,inherit.aes = FALSE) +
  theme_bw()

ggsave(external_corr_plot,filename = "plots/external_corr_plot.png",width = 8,height = 6,units = "in",dpi = 300)
ggsave(external_corr_plot,filename = "plots/external_corr_plot.pdf",width = 8,height = 6,units = "in",dpi = 300)
external_corr_plot
```

```{r seg_counts_sig5}
new_segs <- get_seg_counts(abs_data = abs_data)
old_segs <- get_seg_counts(abs_data = abcel_abs)

new_segs$group <- rep("new",times=nrow(new_segs))
old_segs$group <- rep("old",times=nrow(old_segs))

plot_data_segCount <- rbind(new_segs,old_segs)
plot_data_segCount <- plot_data_segCount[plot_data_segCount$sample %in% patient.meta$SAMPLE_ID,]
plot_data_segCount <- plot_data_segCount[plot_data_segCount$sample %in% plot_data_segCount$sample[plot_data_segCount$group == "old"],]


ggplot(plot_data_segCount,aes(group,segments)) +
  geom_boxplot(aes(fill=group)) +
  geom_signif(comparisons = list(c("new","old")),
              test = "t.test",
              map_signif_level = function(x){formatC(x, format = "e", digits = 2)}) +
  theme_bw()
```

```{r feature_diffs_sig5}
natgen_samp_comp_long <- as.data.frame(natgen_samp_comp) %>%
  rownames_to_column(var="sample") %>%
  pivot_longer(cols = 2:ncol(.))
natgen_samp_comp_long$feat <- gsub(pattern = "[0-9]+|[1-9][0-9]$",replacement = "",perl = T,x = natgen_samp_comp_long$name)
natgen_samp_comp_long$feat <- gsub(pattern = "bpMB",replacement = "bp10MB",x = natgen_samp_comp_long$feat)
natgen_samp_comp_long$cohort <- rep("natgen",times=nrow(natgen_samp_comp_long))

combined_feat <- rbind(natgen_samp_comp_long,samp_comp_long[,-ncol(samp_comp_long)])
combined_feat <- combined_feat[combined_feat$sample %in% patient.meta$SAMPLE_ID,]
combined_feat <- combined_feat[combined_feat$sample %in% combined_feat$sample[combined_feat$cohort == "natgen"],]

combined_feat$name <- factor(combined_feat$name,levels = unique(stringr::str_sort(combined_feat$name,numeric = T)))
combined_feat$feat <- factor(combined_feat$feat,levels = unique(stringr::str_sort(combined_feat$feat,numeric = T)))

test.p <- c()
for(i in unique(combined_feat$name)){
      p <- t.test(x = combined_feat$value[combined_feat$cohort == "natgen" & combined_feat$name == i],
                  y = combined_feat$value[combined_feat$cohort == "britroc" & combined_feat$name == i])$p.value
      test.p <- append(test.p,p)
}
test.p <- data.frame(name=unique(combined_feat$name),
                     feat=combined_feat$feat[match(unique(combined_feat$name),table = combined_feat$name)],
                     pval=round(test.p,digits = 2),
                     qval=round(p.adjust(test.p,method = "bonferroni"),digits = 2))
kable(test.p)
```


```{r feat_diffs_sig5_plot}
seq <- c()
for(i in sort(unique(combined_feat$feat))){
  p <- seq.int(1,length(unique(combined_feat$name[combined_feat$feat == i])),1)
  seq <- append(seq,p)
}

p1 <- ggplot(combined_feat,aes(x = name,y = value)) +
  geom_boxplot(aes(fill=cohort)) +
  geom_tile(aes(x=name)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_x_discrete(labels = seq) +
  geom_signif(aes(x = name,y=value,group=feat),
                annotations = ifelse(test.p$qval < 0.05,"*",NA),
                                     xmin = seq.int(0.5,35.5,1)+0.2,
                                     xmax = seq.int(1.5,36.5,1)-0.2,
                                     y_position = 550,inherit.aes = FALSE)

p2 <- ggplot(combined_feat) +
  geom_tile(aes(x=name,y=1,fill=feat),color="grey10") +
  theme_bw() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(labels=seq) +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(angle=90,hjust = 0),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank()) +
        guides(fill = guide_legend(ncol = 2))

cowplot::plot_grid(p1,p2,nrow = 2,rel_heights = c(0.9,0.1),align = "v",axis = "lr")
```

```{r feat_diffs_corr}
corr_sig5 <- combined_feat[combined_feat$cohort == "natgen",]
corr_sig5$value2 <- combined_feat$value[combined_feat$cohort == "britroc"]

pearson.c <- c()
pearson.p <- c()
for(i in sort(unique(corr_sig5$name))){
  s <- corr_sig5[corr_sig5$name == i,]
  pearson.c <- append(pearson.c,cor.test(x = s$value,y=s$value2,method = "pearson")$estimate)
  pearson.p <- append(pearson.p,cor.test(x = s$value,y=s$value2,method = "pearson")$p.value)
}
corr.data2 <- rbind(round(pearson.c,digits = 2),formatC(pearson.p, format = "e", digits = 2))
colnames(corr.data2) <- unique(corr_sig5$name)
rownames(corr.data2) <- c("corr","p.value")
corr.data2
```

```{r feat_diffs_corr_plot}
corr.data2.t <- as.data.frame(t(corr.data2))
corr.data2.t <- rownames_to_column(corr.data2.t,var = "name")
corr.data2.t$name <- factor(corr.data2.t$name,levels = unique(stringr::str_sort(corr.data2.t$name,numeric = T)))

ggplot(corr_sig5) +
  geom_point(aes(value,value2,color=feat)) +
  facet_wrap(. ~ name, scales = "free") +
  stat_smooth(aes(x = value,y = value2),method = "lm") +
  theme_bw() +
  theme(axis.text = element_blank(),axis.ticks = element_blank(),axis.title = element_blank())
```

```{r session_info}
sessionInfo()
```
