---
title: "BriTROC 30kb CN signature generation"
author: "Philip Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

## Intial setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries

```{r library_load, warning=FALSE}
# Load required libraries with suppressed start-up text
suppressMessages(library(QDNAseqmod))
suppressMessages(library(tidyverse))
suppressMessages(library(kableExtra))
suppressMessages(library(ggplot2))
suppressMessages(library(reshape2))
suppressMessages(library(Biobase))
suppressMessages(library(cowplot))
suppressMessages(library(RColorBrewer))
suppressMessages(library(plotly))
suppressMessages(library(flexmix))
```

### Source functions

```{r source_scripts}
# Load main functions
source("data/britroc_30kb_functions.R")
```

### Load meta data and filter

```{r meta.data}
# Load abs cn meta data and add arx/rlps annotation based on sample name prefix
meta.data <- read.table("../absolute_POST_down_sampling/britroc_30kb_ds_abs_fits.tsv",header = T,sep = "\t")
meta.data$group <- ifelse(grepl("^IM_*", x = meta.data$SAMPLE_ID),"arx","rlps")

# Vector of post-normalisation samples selected to use and vectors of which are arx or rlps
included_samples <- as.character(meta.data$SAMPLE_ID[meta.data$use == "TRUE"])

# Factor of samples in patient order for exposure plots etc
patient_sorted_samples <- factor(meta.data$SAMPLE_ID[order(meta.data$PATIENT_ID)],
                                 levels = unique(meta.data$SAMPLE_ID[order(meta.data$PATIENT_ID)]))
```

### Set misc. parameters

```{r options}
# Cores to use
CORES <- 1

# Colour palette for exposure bar chart matching NatGen
cbPalette <- c(RColorBrewer::brewer.pal(8,"Dark2"),RColorBrewer::brewer.pal(9,"Set1"),"black")
```

## sample information
### Loading absCN data

```{r read_rds}
# Load post-normalise BriTROC absCN profiles and filter to included samples
cn_data <- readRDS("../absolute_POST_down_sampling/britroc_30kb_ds_absCopyNumber.rds")
cn_data <- cn_data[,colnames(cn_data) %in% included_samples]
```

### Patient/sample summary

```{r summarise_sample_data}
#Load meta data for included samples
patient.meta <- meta.data[meta.data$use == "TRUE",]
# Split meta data by patient
per_patient <- split(patient.meta,factor(patient.meta$PATIENT_ID))
# Generate sample, arx, rlps, and paired status for each patient
count.meta <- do.call(rbind,lapply(per_patient, FUN = function(x){
                            patient <- unique(x$PATIENT_ID)
                            sample_count <- length(x$SAMPLE_ID)
                            arx_count <- length(x$SAMPLE_ID[x$group == "arx"])
                            rlps_count <- length(x$SAMPLE_ID[x$group == "rlps"])
                            pair.bool <- all(c("arx","rlps") %in% x$group)
                            f <- data.frame(Patient = patient,
                                            samples = sample_count,
                                            archival = arx_count,
                                            relapse = rlps_count,
                                            paired = pair.bool,row.names = NULL)
                            return(f)
                            })
                          )
# Summarise counts
sum.counts <- data.frame(patients = length(unique(patient.meta$PATIENT_ID)),
                         patient_arx = length(unique(meta.data$PATIENT_ID[meta.data$group == "arx"])),
                         patient_rlps = length(unique(meta.data$PATIENT_ID[meta.data$group == "rlps"])),
                         Paired_patients = sum(count.meta$paired),
                         samples = nrow(patient.meta),
                         samples_arx = length(patient.meta$SAMPLE_ID[patient.meta$group == "arx"]),
                         samples_rlps = length(patient.meta$SAMPLE_ID[patient.meta$group == "rlps"]),
                         Paired_samples = sum(count.meta$samples[count.meta$paired == "TRUE"]))
# Melt patient-level count data for plotting
m.count.meta <- melt(count.meta)[order(melt(count.meta)$value,decreasing = T),]
m.count.meta$Patient <- factor(as.character(m.count.meta$Patient),levels = unique(as.character(m.count.meta$Patient)))
# Add paired info to patient.meta
patient.meta <- merge(patient.meta,count.meta[c("Patient","paired")],by.x = "PATIENT_ID",by.y = "Patient")
```

### Patient/sample summary

```{r sum_counts,echo=FALSE}
knitr::kable(sum.counts) %>% kable_styling()
```

### Patient-level profile counts

```{r count.meta,echo=FALSE}
knitr::kable(count.meta[],row.names = F) %>% kable_styling() %>% scroll_box(height = "200px")
```

## Feature-sample

### Feature distributions

```{r extract_CN_feats_all}
extracted_CN_feats <- extractCopynumberFeatures(CN_data = cn_data, cores = CORES)
plot_feat_dist(featlist = extracted_CN_feats)
```

### Sample by component matrix

```{r sample_by_comp_mat_all}
feat_order <- c(11:13,24:31,17:23,32:36,14:16,1:10)
sample_by_component <- generateSampleByComponentMatrix(extracted_CN_feats)
a_r_status <- meta.data$group[meta.data$SAMPLE_ID %in% rownames(sample_by_component)]
NMF::aheatmap(sample_by_component,annRow = a_r_status,
              fontsize = 7,
              Colv=feat_order,
              legend = T,
              breaks=c(seq(0,199,2),500),
              main="Component x Sample matrix")

```

## Signature quantifications (all)

```{r quant_sigs_all}
sig_quants <- quantifySignatures(sample_by_component)

heatmap(quantifySignatures(sample_by_component), main = "Sample by signature matrix",Rowv = NA)
plot_rel_expo(sig_quants = sig_quants)
```

## Export signature data

```{r export data}
# Save objects as rds data
save(file = "britroc_30kb_signature_data.rds",list = c("patient.meta","sig_quants","sample_by_component"))
# Save patient meta data as csv
write.table(x = patient.meta,
          file = "britroc_30kb_signature_data_meta.tsv",
          quote = FALSE,
          sep = "\t",
          col.names = TRUE,
          row.names = FALSE)
# Save sample_by_component matrix as csv
write.table(x = rownames_to_column(as.data.frame(sample_by_component)),
          file = "britroc_30kb_signature_data_sample_by_comp.tsv",
          quote = FALSE,
          sep = "\t",
          col.names = TRUE,
          row.names = FALSE)
# Save signature exposure matrix as csv
write.table(x = rownames_to_column(as.data.frame(sig_quants)),
          file = "britroc_30kb_signature_data_sig_exposures.tsv",
          quote = FALSE,
          sep = "\t",
          col.names = TRUE,
          row.names = FALSE)

```

## Session info

```{r sessioninfo}
sessionInfo()
```
