---
title: "Analysis of absolute CNAs - sites of relapse"
author: "Philip Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

## Initial steps

### knitr options

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries

```{r load_libraries}
# Load libraries
suppressPackageStartupMessages(suppressWarnings(library(tidyverse)))
suppressPackageStartupMessages(suppressWarnings(library(kableExtra)))
suppressPackageStartupMessages(suppressWarnings(library(RPostgres)))
suppressPackageStartupMessages(suppressWarnings(library(Biobase)))
suppressPackageStartupMessages(suppressWarnings(library(QDNAseqmod)))
suppressPackageStartupMessages(suppressWarnings(library(cowplot)))
suppressPackageStartupMessages(suppressWarnings(library(ggsignif)))
suppressPackageStartupMessages(suppressWarnings(library(fmsb)))
```

```{r funcs}
source("../focal_analysis/data/focal_cna_analysis_funcs.R")
source("../../colour_palettes.R")

get_cna_rates <- function(data=NULL,genes=NULL){
  if(!is.null(genes)){
    data <- data[rownames(data) %in% genes,]
    genes <- unique(data$Gene)
  } else {
    genes <- unique(data$Gene)
  }
  amp_rate <- count_amp_focal(data = data)
  del_rate <- count_del_focal(data = data)
  cna_rate_table <- rbind(data.frame(gene=names(amp_rate),rate=amp_rate,group=rep("amplification",times=length(amp_rate)),row.names = NULL),
                          data.frame(gene=names(del_rate),rate=del_rate,group=rep("deletion",times=length(del_rate)),row.names = NULL))
  return(cna_rate_table)
}

get_cna_changes <- function(data=NULL,genes=NULL,patients=NULL){
  #data <- rownames_to_column(data,var = "Gene")
  if(!is.null(genes)){
    data <- data[rownames(data) %in% genes,]
    genes <- unique(rownames(data))
  } else {
    genes <- unique(rownames(data))
  }
  amp_changes <- as.data.frame(t(data[rownames(data) %in% genes,]))
  amp_changes <- rownames_to_column(amp_changes,var = "SAMPLE_ID") %>%
    mutate(PATIENT_ID=meta.data$PATIENT_ID[match(SAMPLE_ID,meta.data$SAMPLE_ID)]) %>%
    mutate(group=meta.data$group[match(SAMPLE_ID,meta.data$SAMPLE_ID)]) %>%
    relocate(PATIENT_ID,SAMPLE_ID,group) %>%
    pivot_longer(names_to = "gene",cols = 4:ncol(.))
  amp_changes <- amp_changes[amp_changes$PATIENT_ID %in% patients,]
  return(amp_changes)
}

```

```{r read_meta}
meta.data <- read.table("../../copy_number_signatures/britroc_30kb_signature_data_meta.tsv",header = TRUE,sep = "\t")
patient_data <- read.table("../../britroc_cohort_patient_data.tsv",header = T,sep = "\t")
focal_genes_table <- read.table("../focal_analysis/data/focal_CNA_pseudo_bed.txt",header = T,sep = "\t")
ith_table <- read.table("../heterogeneity/data/ith_results_table.tsv",header = T,sep = "\t")
signatures <- read.table("../../copy_number_signatures/britroc_30kb_signature_data_sig_exposures.tsv",
                         header = TRUE,sep = "\t",row.names = 1)
colnames(signatures) <- gsub(colnames(signatures),pattern = "\\.",replacement = "-")
```

```{r db_open}
## Retrieve clinical database login details
clin_config <- config::get("clinDB")
## Establish connection to Postgres DB
britroc_con <- dbConnect(RPostgres::Postgres(),
                         dbname=clin_config$dbname,
                         host=clin_config$host,
                         port = clin_config$port,
                         user = clin_config$user,
                         password = clin_config$password
)
```

```{r get_db_tables}
sample_table <- RPostgres::dbReadTable(britroc_con,name = "sample")

diag_tissue_blocks <- RPostgres::dbReadTable(britroc_con,name = "tissue_blocks")
diag_pre_op <- RPostgres::dbReadTable(britroc_con,name = "pre_relapse_operations")

diag_tissue_table <- left_join(diag_tissue_blocks,diag_pre_op,"histological_id") %>%
                      dplyr::select(histological_id,tissue_site) %>%
                      rename("fk_histological_id"="histological_id")

relapse_tissue_blocks <- RPostgres::dbReadTable(britroc_con,name = "relapse_tissue_samples")
relapse_post_op <- RPostgres::dbReadTable(britroc_con,name = "post_relapse_biopsies")

relapse_tissue_table <- left_join(relapse_tissue_blocks,relapse_post_op,by = c("fk_histological_id"="histological_id")) %>%
                          select("fk_histological_id","anatomical_site") %>%
                          rename("tissue_site"="anatomical_site")

site_table <- left_join(sample_table,diag_tissue_table,"fk_histological_id") %>%
                left_join(.,relapse_tissue_table,"fk_histological_id") %>%
                distinct() %>%
                select("fk_britroc_number","type","name","tissue_site.x","tissue_site.y") %>%
                unite("tissue_site",c("tissue_site.x","tissue_site.y"),sep = ",",remove = TRUE,na.rm = TRUE) %>%
                rename("PATIENT_ID"="fk_britroc_number","SAMPLE_ID"="name") %>%
                filter(type %in% c("archival","relapse")) %>%
                filter(SAMPLE_ID %in% meta.data$SAMPLE_ID)
```

```{r normalise_tissue}
tissue_mapping <- read.table("data/tissue_mapping_V2.txt",header = TRUE,sep = "\t")

site_table$location_curated <- tissue_mapping$location_curated[match(site_table$tissue_site,tissue_mapping$Location.of.Tumour.biopsied)]
site_table$tissue_grouped <- tissue_mapping$tissue_group_curated[match(site_table$tissue_site,tissue_mapping$Location.of.Tumour.biopsied)]

## Some samples have more than one tissue entry for one sample and are dropped
dup_samples <- site_table$SAMPLE_ID[which(duplicated(site_table$SAMPLE_ID))]
length(dup_samples)
site_table <- site_table[which(!site_table$SAMPLE_ID %in% dup_samples),] %>%
                select(SAMPLE_ID,tissue_site,location_curated,tissue_grouped)
table(site_table$location_curated)
table(site_table$tissue_grouped)
tissue_data <- site_table
```

```{r add_tissue_metadata}
meta.data <- left_join(x = meta.data,
                       y = tissue_data,
                       by = "SAMPLE_ID")
head(meta.data)
```

```{r summarise_tissues}
annotation_summary <- as.data.frame(table(meta.data$location_curated,meta.data$group,useNA="ifany")) %>%
                        rename(tissue="Var1",group="Var2",count="Freq") %>%
                        mutate(group = case_when(group == "arx" ~ "diagnosis",
                                                 group == "rlps" ~ "relapse"))

annotation_summary_group <- as.data.frame(table(meta.data$tissue_grouped,meta.data$group,useNA="ifany")) %>%
                                                      rename(tissue="Var1",group="Var2",count="Freq") %>%
                        mutate(group = case_when(group == "arx" ~ "diagnosis",
                                                 group == "rlps" ~ "relapse"))

annotation_summary_plot <- ggplot(annotation_summary) +
  geom_col(aes(tissue,count,fill=group),position="dodge") +
  scale_fill_manual(values = colour_palettes$diagnosis_relapse) +
  xlab("") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

annotation_summary_group_plot <- ggplot(annotation_summary_group) + 
  geom_col(aes(group,count,fill=tissue)) +
  xlab("") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0,vjust = 0.5))

plot_grid(annotation_summary_plot,
          annotation_summary_group_plot,ncol = 1)
```

### Read copy number data

```{r cn_data}
abs_data <- readRDS("../../absolute_POST_down_sampling/britroc_30kb_ds_absCopyNumber.rds")
abs_data <- abs_data[,which(colnames(abs_data) %in% meta.data$SAMPLE_ID[meta.data$use == "TRUE"])]
```

```{r set_ploidy}
ploidys <- pData(abs_data)$ploidy
names(ploidys) <- pData(abs_data)$name
```

```{R cna_calling}
cna_data <- readRDS("../focal_analysis/data/extracted_output.RDS")
cna_calls <- get_cna_calls(data = cna_data)
```

```{r group_samples}
tissue_samples <- split(meta.data$SAMPLE_ID,f = list(meta.data$tissue_grouped),drop = T)
tissue_samples
```
```{r drop_low_counts}
tissue_samples <- tissue_samples[unlist(lapply(tissue_samples,FUN = function(x){length(x) > 2}))]
```


## Analysis
### CNA rates

```{r get_rates}
cna_rates_tissue <- do.call(rbind,lapply(X = names(tissue_samples),FUN = function(x){
  rates <- get_cna_rates(data = cna_calls[,colnames(cna_calls) %in% tissue_samples[[x]]],
                            genes = focal_genes_table$Gene.name)
  rates$tissue <- rep(x,times=nrow(rates))
  return(rates)
}))

focal_rate_plot <- ggplot(cna_rates_tissue) +
  geom_col(aes(x = tissue,y = rate,fill = group),
           position="dodge",color="grey20") +
  #scale_fill_manual(values = colour_palettes$amplification_deletion) +
  labs(title = "") +
  xlab("") +
  ylab("rate (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          axis.text.x = element_text(vjust = 0.5,hjust = 1,angle = 90),
        legend.position = "bottom") +
  scale_fill_manual(values = colour_palettes$amplification_deletion) +
  facet_wrap(. ~ gene,ncol = 3)

saveRDS(focal_rate_plot,file = "plots/cna_rates_tissue.RDS")
ggsave(plot = focal_rate_plot,filename = "plots/cna_rates_tissue.png",width = 8,height = 8,units = "in",dpi = 300)
ggsave(plot = focal_rate_plot,filename = "plots/cna_rates_tissue.pdf",width = 8,height = 8)
focal_rate_plot
```


```{r cna_rates_fisher}
tissue_CNA_rates <- do.call(rbind,lapply(X = names(tissue_samples),FUN = function(x){
  table_group <- as.data.frame(do.call(rbind,fishers_gene_CNA(data = cna_calls,
                            sub_a = tissue_samples[[x]],
                            sub_b = tissue_samples[[x]],
                            genes = focal_genes_table$Gene.name)))
  table_group$tissue <- rep(x,nrow(table_group))
  return(table_group)
  }))

tissue_CNA_rates <- tissue_CNA_rates %>%
                    select(Gene,a,Total_a,group,tissue) %>%
                    group_by(Gene,group)

tissue_CNA_rates_list <- split(tissue_CNA_rates,f = list(tissue_CNA_rates$Gene,tissue_CNA_rates$group))

fisher.test.tissues <- do.call(rbind,lapply(names(tissue_CNA_rates_list),FUN = function(x){
  dat <- as.data.frame(tissue_CNA_rates_list[x])
  #print(dat)
  p.val <- fisher.test(t(dat[,c(2,3)]))$p.value
  x.1 <- str_split(string = x,pattern = "\\.",n = 2,simplify = T)[1]
  x.2 <- str_split(string = x,pattern = "\\.",n = 2,simplify = T)[2]
  row <- data.frame(gene=x.1,group=x.2,p.value=p.val)
  return(row)
}))

sig_tissue_genes <- names(split(fisher.test.tissues[fisher.test.tissues$p.value < 0.05,],
                            f = list(fisher.test.tissues$gene[fisher.test.tissues$p.value < 0.05],
                            fisher.test.tissues$group[fisher.test.tissues$p.value < 0.05]),drop = T))

pairwise.fishers.results <- lapply(sig_tissue_genes,FUN = function(x){
  dat <- as.data.frame(tissue_CNA_rates_list[x])
  t <- as.numeric(t(dat[,2]))
  n <- as.numeric(t(dat[,3]))
  names(n) <- t(dat[,5])

  pair.wise <- pairwise.fisher.test(t,n = n,p.adjust.method = "bonferroni")
  colnames(pair.wise$p.value) <- names(n)[as.numeric(colnames(pair.wise$p.value))]
  rownames(pair.wise$p.value) <- names(n)[as.numeric(rownames(pair.wise$p.value))]
  return(pair.wise)
})
fisher.test.tissues[order(fisher.test.tissues$p.value),]
names(pairwise.fishers.results) <- sig_tissue_genes
pairwise.fishers.results
```

### CNA counts

```{r cna_count}
cna_copies <- get_cna_changes(data = cna_data,genes = focal_genes_table$Gene.name,patients = meta.data$PATIENT_ID) %>%
                mutate(group = case_when(group == "arx" ~ "diagnosis",group == "rlps" ~ "relapse")) %>%
                mutate(tissue = meta.data$tissue_grouped[match(SAMPLE_ID,meta.data$SAMPLE_ID)]) %>%
                filter(!is.na(tissue)) %>%
                filter(tissue != "uncertain")
                # mutate(tissue = ifelse(is.na(tissue),"diagnosis",as.character(tissue)))
```

```{r plot_cna_count}
cna_count_plot <- ggplot(cna_copies) +
  geom_point(aes(x = tissue,y=value,color=tissue),
             position=position_jitterdodge(jitter.width = 0.3),
             alpha=0.2) +
  geom_violin(aes(x = tissue,y=value,color=tissue),fill=NA) +
  ylab("copy number") +
  xlab("") +
  facet_wrap(. ~ gene,scales = "free_y",ncol = 2) +
  theme_bw() +
  theme(legend.position = "bottom")

saveRDS(cna_count_plot,file = "plots/cna_count_tissue.RDS")
ggsave(plot = cna_count_plot,filename = "plots/cna_count_tissue.png",width = 12,height = 8,units = "in",dpi = 300)
ggsave(plot = cna_count_plot,filename = "plots/cna_count_tissue.pdf",width = 12,height = 8)
cna_count_plot
```

```{r cna_count_test}
cna_count_anova <- do.call(rbind,lapply(unique(cna_copies$gene),FUN = function(x){
  gene <- x
  anova.results <- aov(value ~ tissue, data = cna_copies[cna_copies$gene == gene,])
  anova.summary <- summary(anova.results)
  anova.pval <- anova.summary[[1]]$`Pr(>F)`[1]
  anova.post <- TukeyHSD(anova.results)
  
  anova.post.table <- as.data.frame(anova.post$tissue)
  anova.post.table <- anova.post.table[order(anova.post.table$`p adj`),]
  anova.post.table <- anova.post.table[anova.post.table$`p adj` < 0.05,] %>%
                        rownames_to_column(var = "combination") %>%
                        select(combination,`p adj`)
  if(nrow(anova.post.table) > 0){
    out <- data.frame(gene=rep(gene,times=nrow(anova.post.table)),
                      anova_pval=rep(anova.pval,times=nrow(anova.post.table)),
                      posthoc_group=anova.post.table$combination,
                      posthoc_pval=anova.post.table$`p adj`)
  } else {
    out <- data.frame(gene=gene,
                      anova_pval=anova.pval,
                      posthoc_group=NA,
                      posthoc_pval=NA)
  }
  return(out)
}))
cna_count_anova$q.val <- p.adjust(cna_count_anova$posthoc_pval,method = "bonferroni")
cna_count_anova[order(cna_count_anova$anova_pval),]
```

### ITH 

```{r ith_data}
ith_table_tissue <- ith_table %>%
                      mutate(tissue = meta.data$tissue_grouped[match(sample,meta.data$SAMPLE_ID)]) %>%
                      filter(!is.na(tissue)) %>%
                      filter(tissue != "uncertain")
```

```{r ith_plot}
ith_plot <- ggplot(ith_table_tissue) +
  geom_point(aes(tissue,ith,fill=tissue),position="jitter",color="grey50") +
  geom_violin(aes(tissue,ith,fill=tissue),alpha=0.5) +
  #geom_signif(aes(tissue,ith),comparisons = list(c("diagnosis","relapse")),test = "wilcox.test") +
  #scale_fill_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw()

saveRDS(ith_plot,file = "plots/ith_tissue.RDS")
ggsave(plot = ith_plot,filename = "plots/ith_tissue.png",width = 10,height = 8,units = "in",dpi = 300)
ggsave(plot = ith_plot,filename = "plots/ith_tissue.pdf",width = 10,height = 8)
ith_plot
```

```{r test_ith}
res.aov.ith <- aov(ith ~ tissue,data = ith_table_tissue)
summary(res.aov.ith)
TukeyHSD(res.aov.ith)
```

```{r test_signatures}
signatures_table <- signatures %>%
                     rownames_to_column(var = "signature") %>%
                     pivot_longer(cols = 2:ncol(.),names_to = "SAMPLE_ID",values_to = "exposure") %>%
                     mutate(tissue = meta.data$tissue_grouped[match(SAMPLE_ID,meta.data$SAMPLE_ID)]) %>%
                     filter(!is.na(tissue)) %>%
                     filter(tissue != "uncertain")
head(signatures_table)
```

```{r sig_plot}
signature_plot <- ggplot(signatures_table) +
  geom_point(aes(tissue,exposure,fill=tissue),position="jitter",color="grey50") +
  geom_violin(aes(tissue,exposure,fill=tissue),alpha=0.5) +
  #geom_signif(aes(tissue,ith),comparisons = list(c("diagnosis","relapse")),test = "wilcox.test") +
  scale_y_continuous(limits = c(0,1)) +
  facet_wrap(. ~ signature,nrow = 1) +
  theme_bw() +
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 90))

saveRDS(signature_plot,file = "plots/signature_tissue.RDS")
ggsave(plot = signature_plot,filename = "plots/signatures_tissue.png",width = 10,height = 8,units = "in",dpi = 300)
ggsave(plot = signature_plot,filename = "plots/signatures_tissue.pdf",width = 10,height = 8)
signature_plot
```

```{r signature_aov}
signature_tissue_anova <- do.call(rbind,lapply(unique(signatures_table$signature),FUN = function(x){
  sig <- x
  anova.results <- aov(exposure ~ tissue, data = signatures_table[signatures_table$signature == sig,])
  anova.summary <- summary(anova.results)
  anova.pval <- anova.summary[[1]]$`Pr(>F)`[1]
  anova.post <- TukeyHSD(anova.results)
  
  anova.post.table <- as.data.frame(anova.post$tissue)
  anova.post.table <- anova.post.table[order(anova.post.table$`p adj`),]
  anova.post.table <- anova.post.table[anova.post.table$`p adj` < 0.05,] %>%
                        rownames_to_column(var = "combination") %>%
                        select(combination,`p adj`)
  if(nrow(anova.post.table) > 0){
    out <- data.frame(signature=rep(sig,times=nrow(anova.post.table)),
                      anova_pval=rep(anova.pval,times=nrow(anova.post.table)),
                      posthoc_group=anova.post.table$combination,
                      posthoc_pval=anova.post.table$`p adj`)
  } else {
    out <- data.frame(signature=sig,
                      anova_pval=anova.pval,
                      posthoc_group=NA,
                      posthoc_pval=NA)
  }
  return(out)
}))
signature_tissue_anova$q.val <- p.adjust(signature_tissue_anova$posthoc_pval,method = "bonferroni")
signature_tissue_anova_tab <- signature_tissue_anova[order(signature_tissue_anova$anova_pval),]
write.table(signature_tissue_anova_tab,file = "data/signature_tissue_anova_results_table.tsv",quote = F,row.names = F,col.names = T,sep = "\t")
signature_tissue_anova_tab
```
### Diag/Relapse stratification

```{r cn_by_diag_relapse}
obs_table <- as.matrix(table(cna_copies$group[cna_copies$gene == "BRCA1"],
      cna_copies$tissue[cna_copies$gene == "BRCA1"]))

obs_table

tissue_obs_sufficient <- colnames(obs_table)[which(apply(obs_table,MARGIN = 2,FUN = function(x) all(x > 2)))]
tissue_obs_sufficient
cna_copies_stratified <- cna_copies[cna_copies$tissue %in% tissue_obs_sufficient,]
```

```{r get_rates_Strat}
tissue_samples_stratified <- split(meta.data$SAMPLE_ID[meta.data$tissue_grouped %in% tissue_obs_sufficient],
                                   f = list(meta.data$tissue_grouped[meta.data$tissue_grouped %in% tissue_obs_sufficient],
                                            meta.data$group[meta.data$tissue_grouped %in% tissue_obs_sufficient]),drop = T)

cna_rates_tissue_stratified <- do.call(rbind,lapply(X = names(tissue_samples_stratified),FUN = function(x){
  rates <- get_cna_rates(data = cna_calls[,colnames(cna_calls) %in% tissue_samples_stratified[[x]]],
                            genes = focal_genes_table$Gene.name)
  rates$tissue <- rep(x,times=nrow(rates))
  rates <- rates %>%
            separate(tissue,c("tissue","type")) %>%
            mutate(type = case_when(type == "arx" ~ "diagnosis",
                                    type == "rlps" ~ "relapse"))
  return(rates)
}))

focal_rate_plot_amp <- ggplot(cna_rates_tissue_stratified[cna_rates_tissue_stratified$group == "amplification",]) +
  geom_col(aes(x = type,y = rate,fill = type),
           position="dodge",color="grey20") +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  labs(title = "") +
  xlab("") +
  ylab("rate (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          axis.text.x = element_text(vjust = 0.5,hjust = 1,angle = 90),
        legend.position = "bottom") +
  facet_grid(cols = vars(tissue),rows = vars(gene),scales = "free")

focal_rate_plot_del <- ggplot(cna_rates_tissue_stratified[cna_rates_tissue_stratified$group == "deletion",]) +
  geom_col(aes(x = type,y = rate,fill = type),
           position="dodge",color="grey20") +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  labs(title = "") +
  xlab("") +
  ylab("rate (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          axis.text.x = element_text(vjust = 0.5,hjust = 1,angle = 90),
        legend.position = "bottom") +
  facet_grid(cols = vars(tissue),rows = vars(gene),scales = "free")

focal_rate_plot_strat <- plot_grid(focal_rate_plot_amp,focal_rate_plot_del,ncol = 2,labels = c("A","B"))

saveRDS(focal_rate_plot_strat,file = "plots/cna_rates_tissue_stratified.RDS")
ggsave(plot = focal_rate_plot_strat,filename = "plots/cna_rates_tissue_stratified.png",width = 8,height = 8,units = "in",dpi = 300)
ggsave(plot = focal_rate_plot_strat,filename = "plots/cna_rates_tissue_stratified.pdf",width = 8,height = 8)
focal_rate_plot_strat
```

```{r cn_by_diag_relapse_plot}
cn_count_tissue_plot <- ggplot(cna_copies_stratified) +
  geom_point(aes(group,value,color=group)) +
  geom_boxplot(aes(group,value,color=group)) +
  geom_signif(aes(group,value),
              comparisons = list(c("diagnosis","relapse")),
              test = "wilcox.test",vjust = 1.5) +
  facet_grid(cols = vars(tissue),rows = vars(gene),scales = "free") +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

saveRDS(cn_count_tissue_plot,file = "plots/cn_count_tissue_stratified.RDS")
ggsave(plot = cn_count_tissue_plot,filename = "plots/cn_count_tissue_stratified.png",width = 10,height = 8,units = "in",dpi = 300)
ggsave(plot = cn_count_tissue_plot,filename = "plots/cn_count_tissue_stratified.pdf",width = 10,height = 8)
cn_count_tissue_plot
```

```{r cn_sigs_group_by_tissue}
signatures_table_group <- signatures_table %>%
                            mutate(group = meta.data$group[match(SAMPLE_ID,meta.data$SAMPLE_ID)]) %>%
                            mutate(group = case_when(group == "arx" ~ "diagnosis",group == "rlps" ~ "relapse")) %>%
                            filter(tissue %in% tissue_obs_sufficient)
signatures_table_group
```

```{r cn_sigs_group_by_tissue_plot}
cn_sigs_tissueplot1 <- ggplot(signatures_table_group) +
  geom_point(aes(group,exposure,color=group),
             position = position_jitterdodge(jitter.width = 0.3),
             alpha=0.3) +
  geom_violin(aes(group,exposure,color=group),fill=NA) +
  geom_signif(aes(group,exposure),
              comparisons = list(c("diagnosis","relapse")),
              test = "wilcox.test",vjust = 1.5) +
  facet_grid(rows = vars(tissue),cols = vars(signature),scales = "free") +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

cn_sigs_tissueplot2 <- ggplot(signatures_table_group) +
  geom_point(aes(tissue,exposure,color=tissue),alpha=0.4) +
  geom_violin(aes(tissue,exposure,color=tissue),fill=NA) +
  # geom_signif(aes(tissue,exposure),
  #             comparisons = list(c("diagnosis","relapse")),
  #             test = "wilcox.test",vjust = 1.5) +
  facet_grid(rows = vars(group),cols = vars(signature),scales = "free") +
  #scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

saveRDS(cn_sigs_tissueplot1,file = "plots/cn_sigs_tissue_strat.RDS")
ggsave(plot = cn_count_tissue_plot,filename = "plots/cn_sigs_tissue_strat.png",width = 10,height = 8,units = "in",dpi = 300)
ggsave(plot = cn_count_tissue_plot,filename = "plots/cn_sigs_tissue_strat.pdf",width = 10,height = 8)
cn_sigs_tissueplot1
```

```{r ith_group_by_tissue}
ith_table_tissue_group <- ith_table_tissue %>%
                            filter(tissue %in% tissue_obs_sufficient)
ith_table_tissue_group
```

```{r cith_group_by_tissue_plot}
ith_tissueplot1 <- ggplot(ith_table_tissue_group) +
  geom_point(aes(group,ith,color=group),
             position = position_jitterdodge(jitter.width = 0.3),
             alpha=0.3) +
  geom_violin(aes(group,ith,color=group),fill=NA) +
  geom_signif(aes(group,ith),
              comparisons = list(c("diagnosis","relapse")),
              test = "wilcox.test",vjust = 1.5) +
  facet_grid(cols = vars(tissue),scales = "free") +
  scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

ith_tissueplot2 <- ggplot(ith_table_tissue_group) +
  geom_point(aes(tissue,ith,color=tissue),alpha=0.4) +
  geom_violin(aes(tissue,ith,color=tissue),fill=NA) +
  # geom_signif(aes(tissue,ith),
  #             comparisons = list(c("diagnosis","relapse")),
  #             test = "wilcox.test",vjust = 1.5) +
  facet_grid(cols = vars(group),scales = "free") +
  #scale_color_manual(values = colour_palettes$diagnosis_relapse) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))

saveRDS(ith_tissueplot1,file = "plots/ith_tissue_strat.RDS")
ggsave(plot = ith_tissueplot1,filename = "plots/ith_tissue_strat.png",width = 10,height = 8,units = "in",dpi = 300)
ggsave(plot = ith_tissueplot1,filename = "plots/ith_tissue_strat.pdf",width = 10,height = 8)
ith_tissueplot1
```

```{r session_info}
sessionInfo()
```
